// https://developer.mozilla.org/en-US/docs/Web/Events

//An event can be triggered by the user action e.g. clicking the mouse button or tapping keyboard,
//or generated by APIs to represent the progress of an asynchronous task

const red = document.querySelector(".red");
const cyan = document.querySelector(".cyan");
const violet = document.querySelector(".violet");
const orange = document.querySelector(".orange");
const pink = document.querySelector(".pink");

const center = document.querySelector(".center");

const getBGColor = (selesctedElement) =>{
    return window.getComputedStyle(selesctedElement).backgroundColor;
};

var orangeElementColor = (getBGColor(orange));

orange.addEventListener("mouseenter", ()=>{
    center.style.background = orangeElementColor;
});